[package]
name = "example"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]
edition = "2018"

[dependencies]
text-message-derive = { path = "../text-message-derive" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"