[package]
name = "text-message-derive"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
darling = "0.10.2"
wasmtime = "0.12.0"
anyhow = "1.0"
